import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <AntdRegistry>{children}</AntdRegistry>
        <footer className="fixed bottom-0 left-0 right-0 flex items-center justify-between px-6 py-3 bg-cyan-900 border-t border-cyan-100 text-xs text-cyan-50">
          <span>Developed by: Daniel Schwan Monteiro de Sousa</span>
          <span>Dúvidas: ss.daniel096@gmail.com</span>
        </footer>
      </body>
    </html>
  );
}
